# Generated by Django 3.2.12 on 2022-04-02 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.CharField(blank=True, max_length=150, null=True)),
                ('stock_name', models.CharField(blank=True, max_length=150, null=True)),
                ('stock_identity', models.CharField(blank=True, max_length=150, null=True)),
                ('stock_id', models.CharField(blank=True, max_length=150, null=True)),
                ('action_type', models.CharField(blank=True, max_length=150, null=True)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('action_ratio', models.CharField(blank=True, max_length=150, null=True)),
                ('agm_egm', models.DateField(blank=True, null=True)),
                ('ex_date', models.DateField(blank=True, null=True)),
                ('rd', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('remarks', models.CharField(blank=True, help_text='remarks for your customers', max_length=500, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=150, null=True)),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('buy_price', models.CharField(blank=True, max_length=150, null=True)),
                ('exit_price', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorpActionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('security_name', models.CharField(blank=True, max_length=150, null=True)),
                ('security_id', models.CharField(blank=True, max_length=150, null=True)),
                ('security_number', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.CharField(blank=True, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, help_text='Enter your mobile number', max_length=150, null=True, verbose_name='Mobile Number')),
                ('agreement', models.BooleanField(default=False)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('user_type', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_phone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.CharField(blank=True, max_length=150, null=True)),
                ('stock_record', models.TextField()),
                ('record_date', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.coaction')),
            ],
        ),
    ]
