# Generated by Django 3.2.12 on 2022-02-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaction',
            name='stock_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='coaction',
            name='stock_identity',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
