# Generated by Django 3.2.12 on 2022-02-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_corpactionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpactionrecord',
            name='security_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='corpactionrecord',
            name='security_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='corpactionrecord',
            name='security_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
