# Generated by Django 3.2.12 on 2022-02-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20220208_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, help_text='Enter your mobile number', max_length=150, null=True)),
                ('user_type', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
