# Generated by Django 3.2.12 on 2022-02-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_userphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaction',
            name='company_event',
        ),
        migrations.AddField(
            model_name='coaction',
            name='agm_egm',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coaction',
            name='rd',
            field=models.DateField(auto_now=True),
        ),
    ]
