# Generated by Django 3.2.12 on 2022-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20220210_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaction',
            name='buy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coaction',
            name='buy_price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='coaction',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coaction',
            name='exit_price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
