# Generated by Django 3.2.12 on 2022-02-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20220210_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaction',
            name='remarks',
            field=models.CharField(blank=True, help_text='remarks for your customers', max_length=500, null=True),
        ),
    ]
