# Generated by Django 3.2.12 on 2022-02-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_coaction_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaction',
            name='action_ratio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='coaction',
            name='ex_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userphone',
            name='mobile',
            field=models.CharField(blank=True, help_text='Enter your mobile number', max_length=150, null=True, verbose_name='Mobile Number'),
        ),
    ]
