# Generated by Django 3.2.12 on 2022-02-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20220211_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphone',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
    ]
