# Generated by Django 3.2.12 on 2022-03-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_scandata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpactionrecord',
            name='record_date',
            field=models.DateField(),
        ),
    ]
