# Generated by Django 3.2.12 on 2022-03-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_corpactionrecord_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpactionrecord',
            name='message',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
