databases:
  - name: wealth
    databaseName: wealth
    user: wealth

services:
  - type: web
    name: wealth
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wealth.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wealth
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
envVarGroups:
  - name: wealth